# Generated by Django 4.2 on 2024-09-12 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
