# Generated by Django 4.2 on 2024-09-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_news_category'),
        ('news', '0002_comment'),
    ]

    operations = [
    ]
