# Generated by Django 4.2 on 2024-09-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="point",
            field=models.IntegerField(default=0),
        ),
    ]
